### ISSUE TITLE
Syntax error at line 361 main.py

### ISSUE THREAD

**Issue by khakimin** [detecttechnologies/Thermal_Image_Analysis#12]
Hi, there is syntax error when I try to run main.py, can you check?

  File "main.py", line 361
    self.renderText(self.overlays, f"l{self.lineNum}", center)
                                                    ^
SyntaxError: invalid syntax

**Comment by khakimin** [comment]
![syntaxerror](https://user-images.githubusercontent.com/5679535/169237027-3b811209-8a72-4f7c-a85e-63d381fcd5d5.png)

**Comment by khakimin** [comment]
okay when I run with python3, main.py works.

**Comment by rsnk96** [comment]
Thanks for sharing your learnings @khakimin
