### ISSUE TITLE
Opening sequentialla all frames in a seq file

### ISSUE THREAD

**Issue by SReich-EMI** [detecttechnologies/Thermal_Image_Analysis#2]
This project is very helpful for me. I’m using a FLIR thermal camera and want to analyze the movies with Python. With this code I can open the seq files directly in python. I want to extract temperatures within all frames of one movie, therefore I have to open all frames after each other. Until now, I don’t figured out, how I can open other frames than the first.
I don’t require it to be implemented into this code, because I only want to read in the frames an work with them in Python by numpy.
Can you tell me, how I can get access to the later frames?

Kind regards
Stefan Reich

**Comment by rakshith95** [comment]
Hello, 
[This](https://exiftool.org/forum/index.php?topic=5279.0) thread outlines splitting an SEQ to its individual fff files. Use the `hexdump` command to get the hex pattern generated by your camera

**Comment by rakshith95** [comment]
The python code to split an SEQ into frames has also been added to this repo

**Comment by rsnk96** [comment]
@SReich-EMI the codes that @rakshith95 is referring to has been shifted to the class `CSeqVideo` in `CThermal.py`, and the details of how to use it have been updated in the README. Do let us know if you have any more queries
