### ISSUE TITLE
PIL.UnidentifiedImageError

### ISSUE THREAD

**Issue by likilias** [detecttechnologies/Thermal_Image_Analysis#6]
Hi, I am trying to run the command:

python thermal_analysis.py <flir_image_path>

but its throwing this error:

PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x00000232575A1B88>

 I did run requirements.txt and do the following:
Download exiftool ,
Extract 'exiftool(-k).exe' to the folder where I'm running the code from,
Rename it to 'exiftool.exe',
what do I do? Any kind of suggestions will be helpful. Thank you.

**Comment by rakshith95** [comment]
I assume you're running it in Windows. If possible, can you share your flir file?
Haven't seen this error before.

**Comment by likilias** [comment]
Thank you for your reply.Yes,I'm running it in Windows.This is my  flir file.
![211](https://user-images.githubusercontent.com/81793208/113421465-bbb2d380-93fd-11eb-8ef3-c0039daa769b.jpg)

**Comment by rakshith95** [comment]
Can you upload the original file? I wanted to test it with the program. This seems to be a normal jpg image, not a FLIR thermal image.

**Comment by likilias** [comment]
Sorry, there was a little error in the picture I sent before. Now I sent the picture in PNG format which I collected from the laboratory through the infrared thermal imager.
![211](https://user-images.githubusercontent.com/81793208/113462752-13305e00-9455-11eb-9f3f-49e92ffca093.Png)

**Comment by rakshith95** [comment]
What camera did you use to take this image?
While it is a 'thermal image', it doesn't contain any of the required metadata to use with this software, eg. raw sensor values.

**Comment by likilias** [comment]
OK, I see. There is a problem with my infrared thermal image, which leads to a program error. Well, if you can, could you please send me an infrared thermal image of a person's face that can be used for my follow-up study? Thank you very much for your time to help me solve the problem.



            
            
                
                    
                            
                                
                            
                            
                                15227887681
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        Signature is customized by Netease Mail Master


            On 04/03/2021 19:49, rakshith95 wrote: 
What camera did you use to take this image?
While it is a 'thermal image', it doesn't contain any of the required metadata to use with this software, eg. raw sensor values.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/detecttechnologies/Thermal_Image_Analysis/issues/6#issuecomment-812854455",
"url": "https://github.com/detecttechnologies/Thermal_Image_Analysis/issues/6#issuecomment-812854455",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by rakshith95** [comment]
I don't have any unfortunately. You could try the FLIR forums or reddit or something. Closing this issue
